// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsGvBqYiwjvv9lYx6YCztO299U8--FG2k',
    appId: '1:529739976630:web:ac9e96de9e17ae214c3b17',
    messagingSenderId: '529739976630',
    projectId: 'fir-2auth-e22cc',
    authDomain: 'fir-2auth-e22cc.firebaseapp.com',
    storageBucket: 'fir-2auth-e22cc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYj1wrKa5lbAHL8U9r7cuetN4FznrtG_4',
    appId: '1:529739976630:android:cc7929060a0b37184c3b17',
    messagingSenderId: '529739976630',
    projectId: 'fir-2auth-e22cc',
    storageBucket: 'fir-2auth-e22cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1oRm8QQNiHcg1RfZloqmn2HlMQeogl5M',
    appId: '1:529739976630:ios:5875ceb669ae08d24c3b17',
    messagingSenderId: '529739976630',
    projectId: 'fir-2auth-e22cc',
    storageBucket: 'fir-2auth-e22cc.appspot.com',
    iosBundleId: 'com.example.firebase2project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1oRm8QQNiHcg1RfZloqmn2HlMQeogl5M',
    appId: '1:529739976630:ios:1a62f6b56655eec34c3b17',
    messagingSenderId: '529739976630',
    projectId: 'fir-2auth-e22cc',
    storageBucket: 'fir-2auth-e22cc.appspot.com',
    iosBundleId: 'com.example.firebase2project.RunnerTests',
  );
}
